/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "suma.h"

int *
suma_1_svc(dupla_int *argp, struct svc_req *rqstp)
{
	static int  result[4];
	static char resultado;

	/*
	 * insert server code here
	 */
	printf("server is working \n");
	printf("parameters: %d, %d \n", argp->a, argp->b);
	
	result[0] = argp->a + argp->b;
	printf("returning +: %d \n", result[0]);	
result[1] = argp->a - argp->b;
	printf("returning -: %d \n", result[1]);
result[2] = argp->a * argp->b;
	printf("returning -: %d \n", result[2]);
result[3] = argp->a / argp->b;
	printf("returning -: %d \n", result[3]);
		resultado=("suma= % %d resta= %d multiplicacion= %d division %d", result[0], result[1], result[2], result[3]);
	return &resultado;

}
